name: End 2 end tests
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  end2end:
    name: End 2 end execution
    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-drone@v1
        with:
          version: '0.8.1'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true   
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'qae2e'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: drone exec --pipeline=wfm
        env:
          DRONE_SERVER: ${{ secrets.DRONE_SERVER }}
          DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}
        if: steps.check.outputs.triggered == 'true'   
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'